# -*- coding: utf-8 -*-
"""aula2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qHSMUB4VjdC2n91v_8pTFAXKKhETKCmM
"""

[1] #Manipulação dos dados
import pandas as pd

#Visualização

#Machine Learning

df = pd.read_csv("KAG_conversion_data.csv")

type(df)

df.head()

df.tail()

df.columns

df.index

df.shape

linhas,colunas=df.shape

print(f"O número de linhas é {linhas}")

type(df)

ser_interest=df["interest"]

type(ser_interest)

df.info()